version: 3
pullapprove_conditions:
- condition: "base.ref == 'master'"
  unmet_status: success
  explanation: "Review not required unless merging to master"
- "'hotfix' not in labels"  # when using the string type, the default status is "success"
- condition: "'WIP' not in title"
  unmet_status: pending
  explanation: "Work in progress"
- condition: "not draft"
  unmet_status: pending
  explanation: "Waiting to send reviews as PR is in draft"

groups:
  devops:
    conditions:
    - >
      'config/*.yml' in files.exclude("*/locales/*") or
      'Jenkinsfile' in files or
      '*Docker*' in files or
      '*docker*' in files
    reviewers:
      users:
        - mathcantin
        - tdompierre
    reviews:
      required: 1
      request: 0
      request_order: shuffle
      author_value: 1

  leads:
    reviewers:
      teams:
      - leads
    reviews:
      required: 1
      request: 0
      author_value: 1

  developers:
    reviewers:
      teams:
      - developers
      - leads
    reviews:
      required: 1
      request: 0

  libraries-be:
    conditions:
    - "'Gemfile*' in files"
    reviewers:
      teams:
      - libraries-be
    reviews:
      required: 1
      request: 0
      author_value: 1

  libraries-fe:
    conditions:
    - "'package.json' in files or 'tsconfig.json' in files"
    reviewers:
      teams:
      - libraries-fe
    reviews:
      required: 1
      request: 0
      author_value: 1
