version: 3

pullapprove_conditions:
- condition: "base.ref == 'master'"
  unmet_status: success
  explanation: "Review not required unless merging to master"
- "'hotfix' not in labels"  # when using the string type, the default status is "success"
- condition: "'WIP' not in title"
  unmet_status: pending
  explanation: "Work in progress"
- condition: "not draft"
  unmet_status: pending
  explanation: "Waiting to send reviews as PR is in draft"
- condition: "'DO NOT MERGE' not in title"
  unmet_status: failure
  explanation: "Do not merge this PR"
  
groups:
  lead:
    conditions:
    - "files.include('*')"
    reviewers:
      users:
        - mathcantin
        - tdompierre
    reviews:
      required: 1
      request: 1
      request_order: shuffle
      author_value: 1

  devops:
    conditions:
    - "files.include('*')"
    reviewers:
      teams:
        - devops
    reviews:
      required: 2
      request: 2
      request_order: shuffle

