version: 3
overrides:
- if: "base.ref != 'master' and base.ref != 'migration'"
  status: success
  explanation: "Review not required unless merging to master or migration"
- "'hotfix' in labels"  # when using the string type, the default status is "success"
- if: "'WIP' in title"
  tatus: pending
  explanation: "Work in progress"
- if: "draft"
  status: pending
  explanation: "Waiting to send reviews as PR is in draft"

groups:
  devops:
    conditions:
    - >
      'config/*.yml' in files.exclude("*/locales/*") or
      'Jenkinsfile' in files or
      '*Docker*' in files or
      '*docker*' in files
    reviewers:
      teams:
        - devops
    reviews:
      required: 1
      request: 0
      request_order: shuffle
      author_value: 1

  leads:
    reviewers:
      teams:
      - leads
    reviews:
      required: 1
      request: 0
      author_value: 1

  developers:
    reviewers:
      teams:
      - developers
      - leads
    reviews:
      required: 1
      request: 0

  libraries-be:
    conditions:
    - >
      'Gemfile*' in files or
      'db/migrate/*' in files
    reviewers:
      teams:
      - libraries-be
    reviews:
      required: 1
      request: 0
      author_value: 0

  libraries-fe:
    conditions:
    - "'package.json' in files or 'tsconfig.json' in files"
    reviewers:
      teams:
      - libraries-fe
    reviews:
      required: 1
      request: 0
      author_value: 1
