version: 3

overrides:
- if: "base.ref != 'master'"
  status: success
  explanation: "Review not required unless merging to master"
# - "'hotfix' in labels"  # when using the string type, the default status is "success"
# - if: "draft or 'WIP' in title"
#   status: pending
#   explanation: "Work in progress"
# - if: "'DO NOT MERGE' in title"
#   status: failure
#   explanation: "Do not merge this PR"
  
groups:
  lead:
    conditions:
    - "files.include('*')"
    reviewers:
      users:
        - mathcantin
        - tdompierre
    reviews:
      required: 1
      request: 1
      request_order: shuffle
      author_value: 0

  devops:
    conditions:
    - "files.include('*')"
    reviewers:
      teams:
        - devops
    reviews:
      required: 2
      request: 2
      request_order: shuffle

