  version: 3
  pullapprove_conditions:
  - "'WIP' not in title"
  - "base.ref == 'master'"
  - "'hotfix' not in labels"

  groups:
    prodteam:
      conditions:
      - "'*.yml' in files or 'Jenkinsfile' in files or '*Dockerfile*' in files or '*docker-compose*' in files"
      reviewers:
        teams:
        - team-production
      reviews:
        required: 1
        request: 1
        request_order: random

    leads:
      conditions:
      - "files.include('*')"
      reviewers:
        teams:
        - leads
      reviews:
        required: 1
        request: 1
        request_order: random

    developers:
      conditions:
      - "files.include('*')"
      reviewers:
        teams:
        - developers
        - leads
      reviews:
        required: 2
        request: 2
        request_order: random   
