version: 3
pullapprove_conditions:
- "'WIP' not in title"
- "base.ref == 'master'"
- "'hotfix' not in labels"

groups:
  prodteam:
    conditions:
    - >
      '*.yml' in files.exclude("*/locales/*") or
      'Jenkinsfile' in files or
      '*Docker*' in files or
      '*docker*' in files
    reviewers:
      teams:
      - team-production
    reviews:
      required: 1
      request: 0
      author_value: 1

  leads:
    reviewers:
      teams:
      - leads
    reviews:
      required: 1
      request: 0
      author_value: 1

  developers:
    reviewers:
      teams:
      - developers
      - leads
    reviews:
      required: 1
      request: 0

  libraries:
    conditions:
    - "'Gemfile*' in files or 'package.json' in files"
    reviewers:
      teams:
      - leads
      - team-production
    reviews:
      required: 1
      request: 0
